### ISSUE TITLE
use of `Topic.comment_count`

### ISSUE THREAD

**Issue by hemache** [Mehdi6/bootcamp-hackernews#8]
why not rely on dynamic counting using Django ORM, something like
```python
topic.comments.count()
```

**Comment by Mehdi6** [comment]
I spoke about this issue with @dermoumi. He suggested that I use a [property](https://github.com/Mehdi6/bootcamp-hackernews/blob/873237e491517f842e130a02cd1dc16cbc025bb0/services/models.py#L22) instead, which seams to work pretty fine.

**Comment by hemache** [comment]
yep, as long as we don't actually store the count in a database column.
side question, why not `return self.comment_set.count()` instead of `Comment.objects.filter(topic=self).count()` ?

**Comment by Mehdi6** [comment]
[fixed](https://github.com/Mehdi6/bootcamp-hackernews/blob/c1d01df0325644032db1885f49d6c89f93acd6fe/services/models.py#L23), used the `related_name=comments` in the definition of the comment model and replaced `Comment.objects.filter(topic=self).count()` with `self.comments.count()`
